### ISSUE TITLE
snaps.py

### ISSUE THREAD

**Issue by hursty1** [Begintocodewithpython/samples#1]
When following along with the book i've encountered an issue in chapter 10 page 364.

It trys to call the play_note function from snaps.py

it was a simple fix by adding the following to the snaps file

```
def play_note(note):
    ''' 
    Plays the note sound file 1-12
    '''
    filepath = str('MusicNotes\\' + str(note) + '.wav')
    play_sound(filepath)
```

**Comment by CrazyRobMiles** [comment]
Oooh. Thanks so much for letting me know. I've fixed the sample code on
GitHub.

best wishes

Rob Miles
